library(dplyr)
library(Seurat)  # 3.2.1
library(patchwork)
library(Matrix)
library(data.table)
library(reshape2)
library(ggplot2)
library(gridExtra)
library(gridGraphics)
library(RColorBrewer)


make_2d_tsne = function(input_file, output_name, df) {
  selected = read.table(input_file, header = TRUE, sep = "\t", row.names="cell")
  # these are the selected cells 
  to_highlight = rownames(selected)
  
  g = DimPlot(df, reduction = "tsne_2D", cells.highlight=to_highlight) + 
      ggtitle(output_name) + NoLegend() +   ylab("2D t-SNE_2")  + xlab("2D t-SNE_1")

  return(g)
}

make_3d_tsne = function(input_file, output_name, df) {
  selected = read.table(input_file, header = TRUE, sep = "\t", row.names="cell")
  # these are the selected cells 
  to_highlight = rownames(selected)
  
  g = DimPlot(df, reduction = "tsne_3D", cells.highlight=to_highlight) + 
    ggtitle(output_name) + NoLegend() + ylab("3D t-SNE_2") + xlab("3D t-SNE_1")
  return(g)
}

make_umap = function(input_file, output_name, df) {
  selected = read.table(input_file, header = TRUE, sep = "\t", row.names="cell")
  # these are the selected cells 
  to_highlight = rownames(selected)
  
  g = DimPlot(df, reduction = "umap", cells.highlight=to_highlight) + 
    ggtitle(output_name) + NoLegend()
  return(g)
}


# To save normalized and scaled expression data for all genes
load("raw_counts_mat.rdata")  # human brain
input_data <- CreateSeuratObject(counts = raw_counts_mat, min.cells = 3, min.features = 200)
input_data <- NormalizeData(input_data, normalization.method = "LogNormalize", scale.factor = 10000)
input_data <- ScaleData(input_data)  # mean 0, STD 1
adf = GetAssayData(input_data, slot = "scale.data") 
write.table(as.matrix(adf), sep=",", file='norm_scale_exp.csv', quote=FALSE)

# To save cell-cell similarity and KNN graph
load("raw_counts_mat.rdata")  # human brain
input_data <- CreateSeuratObject(counts = raw_counts_mat, min.cells = 3, min.features = 200)
# to normalize and scale expression data, for top features
input_data <- NormalizeData(input_data, normalization.method = "LogNormalize", scale.factor = 10000)
input_data <- FindVariableFeatures(input_data) 
input_data <- ScaleData(input_data)  # mean 0, STD 1
input_data <- RunPCA(input_data, features = VariableFeatures(object = input_data), npcs = 40)

# How to get KNN and SNN graph (FindVariableFeatures required)
input_data <- FindNeighbors(input_data, dims = 1:40, compute.SNN = TRUE) # k = 40 by default
write.table(as.matrix(input_data$RNA_nn), sep=",", file="KNN_graph.csv", quote=FALSE)
write.table(as.matrix(input_data$RNA_snn), sep=",", file="SNN_graph.csv", quote=FALSE)

input_data <- FindClusters(input_data)
# dimensionality reduction of all cells from expression data
input_data <- RunTSNE(input_data, dims=1:40, reduction.name="tsne_2D")
input_data <- RunUMAP(input_data, dims=1:40)
input_data <- RunTSNE(input_data, dims=1:40, dim.embed=3, reduction.name="tsne_3D")

exit()

######
# To print the 2D t-SNE with the paper's identity labels
original = DimPlot(input_data)
file_name_or = "original_2DtSNE.png"
png(file_name_or)
print(original)
dev.off()


######
# Examples for how to make 2D and 3D t-SNE and UMAP plots
# the solution file from C-TULPSE is named ${output_string}_${k}_LPonLSCC.txt

tsne_2_250 = make_2d_tsne('M1_250_LPonLSCC.txt', '250', input_data)
tsne_3_250 = make_3d_tsne('M1_250_LPonLSCC.txt', '250', input_data)
umap_250 = make_umap('M1_250_LPonLSCC.txt', '250', input_data)
pdf("Example_M1_250.pdf")
grid.arrange(tsne_2_250, tsne_3_250, umap_250, nrow=1)
dev.off()


#######
# Example to plot k vs. silhouette score
# k_vs_obj_sil*.txt must contain at least two columns 'k' and 'Silhouette', 
# with corresponding values

sum_df = read.table("k_vs_obj_sil_M1.txt", header = TRUE, sep = "\t")
# turn it into a line plot
sum_plot = ggplot(data=sum_df, aes(x=k, y=Silhouette)) +
  geom_line() +
  geom_point() + theme_classic()


#######
# Example to plot percent composition over k
# *_composition.txt can be generated by running the python script 'get_comp.py'
# and adding a header that contains the columns 'k', 'percent composition', and 'cell type'

make_comp_line = function(in_file) {
  df = read.table(in_file, header = TRUE, sep = "\t")
  
  g = ggplot(data=df, aes(x=k, y=percent.composition, group=cell.type)) +
    geom_line(aes(color=cell.type)) +
    geom_point(aes(color=cell.type)) + theme_classic() + ylab("Percent composition") + labs(color='Cell-type') +
    theme(legend.title = element_blank(), legend.key.size = unit(0.3, 'cm'))
  
  return(g)
  
}

m1_comp = make_comp_line("m1_composition.txt")
